In [1]:
import pandas as pd
import numpy as np

# Min_Max method

In [2]:
X = np.array([[1,-1,2],[2,0,0],[0,1,-1]])
X

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1, -1]])

In [3]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
X_mm = minmax_scaler.fit_transform(X)
X_mm

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [4]:
X_new = np.array([[-3,-1,4]])
X_new_mm = minmax_scaler.transform(X_new)
X_new_mm

array([[-1.5       ,  0.        ,  1.66666667]])

### split ( x ,y , binary)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
x_mm = minmax_scaler.fit_transform()
x_mm

In [ ]:
mm_df = pd.DataFrame(X_mm, columns = df.iloc[].columns)
mm_df

In [ ]:
df_final = pd.concat([mm_df,y, binary], axis = 1)
df_final

# z_score method

### split(x,y,binary)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_ss = sc.fit_transform(X)
x_ss

In [ ]:
ss_df = pd.DataFrame(X_sc, columns = df.iloc[].columns)
ss_df

In [ ]:
df_final = pd.concat([ss_df, binary,y], axis = 1)
df_final